//Defines a series of constant strings for use in the game engine
//By Simon Jones

#include "strings.h"

const char* DISPLAY_QUEUE_ERROR_MESSAGE = "ERROR DQ\00";

const char* SCORE_STRING = "SCORE\00";
const char* LEVEL_STRING = "LEVEL\00";
const char* NEXT_STRING = "NEXT\00";

const char* FINAL_SCORE_STRING = "FINAL SCORE\00";
const char* LEVELS_CLEARED_STRING = "LEVEL REACHED\00";
const char* THANKS_STRING = "THANK YOU FOR PLAYING\00";
const char* TEMP_GAME_OVER_STRING = "GAME OVER\00";
const char* ROWS_COMPLETED_STRING = "ROWS COMPLETED\00";

const char* ROTATE_HELP_MSG = "ROTATE\00";
const char* DROP_HELP_MSG = "QUICK DROP\00";
const char* LEFT_HELP_MSG = "LEFT\00";
const char* RIGHT_HELP_MSG = "RIGHT\00";

const char* AUTHOR_STRING = "BY SIMON JONES\00";
const char* VERSION_STRING = "VERSION\00";
const char* TEMP_TETRIS_STRING = "TETRIS\00";

const char* DEBUG_TITLE_STRING = "GAME DEBUG";
const char* DEBUG_AVERAGE_INPUT_DELAY_STRING = "AVG INPUT DELAY TICKS";
const char* DEBUG_MAXIMUM_INPUT_DELAY_STRING = "MAX INPUT DELAY TICKS";
const char* DEBUG_SYSTEM_TICK_RATE_STRING = "FREERTOS TICK RATE MS";
const char* GAME_REFRESH_RATE_STRING = "GAME REFRESH RATE TICKS";
const char* GAME_REFRESH_RATE_ERROR_STRING = "REFRESH RATE ERROR %\nA        M";
const char* INPUT_DELAY_STRING = "INPUT DELAY TICKS\nA        M";

const char* ANY_KEY_TO_CONTINUE_STRING = "ANY BUTTON TO START";
